[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "snc"
description = "Make sequence logos using Felsenstain's phylogenetically independent contrast metod to take evolution into account"
authors = [{name = "Haolin Guo"}]
maintainers = [{name = "Lars Arvestad", email = "arve@math.su.se"}]
classifiers = ["License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)"]
dynamic = ["version"]
requires-python = ">=3.10"
dependencies = [
	     "biopython>=1.8",
	     "weblogo>=0.9"
]

[project.scripts]
phyinc = "phyinc:main"


[tool.setuptools.dynamic]
version = {attr = "phyinc.version.__version__"}


