[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "phyinc"
description = "Make sequence logos using Felsenstain's phylogenetically independent contrast metod to take evolution into account"
readme = "README.md"
authors = [{name = "Haolin Guo"}]
maintainers = [{name = "Lars Arvestad", email = "arve@math.su.se"}]
classifiers = ["License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)"]
dynamic = ["version"]
requires-python = ">=3.10"
dependencies = [
	     "matplotlib",
	     "biopython>=1.8",
	     "weblogo>=3.9"
]

[project.scripts]
phyinc = "phyinc.phyinc:main"


[tool.setuptools.dynamic]
version = {attr = "phyinc.version.__version__"}


[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
